name: fkmeup
description: Gamified productivity execution system.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  path_provider: ^2.1.4
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.4.0
  intl: ^0.19.0
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/env/.env

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  isar_community_generator: ^3.3.0
